server:
  port: 8084

spring:
  application:
    name: cs-accounts-events-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/tuum_banking
    username: tuum_user
    password: tuum_password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: tuum_user
    password: tuum_password
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
        default-requeue-rejected: false
    # Disable auto-configuration of Jackson2JsonMessageConverter
    message-converter: simple

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuum.csaccountseventsconsumer.model

logging:
  level:
    com.tuum.csaccountseventsconsumer: DEBUG
    org.springframework.amqp: DEBUG
