server:
  port: 8084
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: cs-accounts-events-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/tuum_banking
    username: tuum_user
    password: tuum_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        connection:
          isolation_level: SERIALIZABLE
        jdbc:
          batch_size: 20
          fetch_size: 20

  rabbitmq:
    host: localhost
    port: 5672
    username: tuum_user
    password: tuum_password
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false
    # Disable auto-configuration of Jackson2JsonMessageConverter
    message-converter: simple

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuum.common.domain.entities

# Logging configuration for clean error handling
logging:
  level:
    com.tuum.csaccountseventsconsumer: INFO
    com.tuum.common.exception: DEBUG
    org.springframework.amqp: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    org.apache.ibatis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
